spring:
  application:
    name: service-B
server:
  port: 1121

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:1111/eureka/
      #这个地址就是在 Eureka 服务端的 application.yml 上暴露出的服务地址（这行后面加注释，可能会报错）