---
server:
  port: 8762
---
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    #  表示是否将自己注册到Eureka Server，默认为true
    #    registerWithEureka: false
    #    表示是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/,http://127.0.0.1:8763/
    server:
      enableSelfPreservation: false
      evictionIntervalTimerInMs: 4000